Table Branches {
    id int [pk, increment]
    name varchar(100) [not null]
    address varchar(255)
    phonenumber varchar(15)
    active boolean [default: true]

}

Table Categories {
    id int [pk, increment]
    name varchar(100) [not null]
    description text
}